/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'instituteName' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'instituteAddress' : IDL.Text,
  'course' : IDL.Text,
  'regNo' : IDL.Text,
});

export const idlService = IDL.Service({
  'getStudent' : IDL.Func([], [Student], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'instituteName' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'instituteAddress' : IDL.Text,
    'course' : IDL.Text,
    'regNo' : IDL.Text,
  });
  
  return IDL.Service({ 'getStudent' : IDL.Func([], [Student], ['query']) });
};

export const init = ({ IDL }) => { return []; };